- README.md
These are needed in order for this plugin to function.
Fixes #2
> add instructions to migrate external links migrations

- app/assets/javascript/pageflow/linkmap_page/editor/models/area.js
Prevent text areas to be displayed as "(Unknown)" in editor area list.
> Use info box title as title for text only areas

- app/assets/javascript/pageflow/linkmap_page/editor/views/edit_area_view.js
Not accessible with mouse anyway since overlays close when hotspot is left.
> Disable links in overlay boxes

- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap_panorama.js
When the scroll area is restricted, we center it in the viewport. The
old logic did this by translating an inner element of the
scroller. This had two problems:
* It did not consider the maximal allowed translation causing the
panorama not to cover the viewport in some cases.
* It moves the logo off position.
Instead consider the translation required for centering when
positioning the scoller's inner element.
> Ensure viewport is covered when scroll area restricted

- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap_lookaround.js
Do not start scrolling when tapping in page margin.
> Prevent scrolling via mousemove on mobile platform

- pageflow-linkmap-page.gemspec
`0.12` will be released as `12.0`.
> Require Pageflow 12

- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap/area_redraw.js
For the hover video variant, there is no canvas which needs to be
redrawn. Check whether canvas exists first.
> Fix hover video variant in published entry

- app/helpers/pageflow/linkmap_page/areas_helper.rb
- spec/helpers/pageflow/linkmap_page/areas_helper_spec.rb
Only replace digit-only segments with `:id_partition` placeholder.
> Make mask image url template generation more robust

- Gemfile
Can be removed again once Bundler no longer shows this behavior.
> Set railties version to prevent infinite loop in bundle install

- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap_panorama.js
Only needed if opened in same tab.
> Do not show load indicator for external link opening new tab

- lib/pageflow/linkmap_page/engine.rb
- spec/spec_helper.rb
- spec/support/config/factory_bot.rb
* Let `pageflow-support` require `factory_bot` to prevent loading
models before Paperclip test env setup has been applied.
* Register Paperclip IO data uri adapter which is now opt-in.
> Adapt to Pageflow 13

- app/assets/javascript/pageflow/linkmap_page/page_type.js
Integrate with background media feature of Pageflow 12.3:
* Mute background media when video playback with sound fails
* Unmute video when background media is unmuted
* Unmute background media when playing an audio hotspot
* Play video muted on platforms that do not support autoplay
REDMINE-15771
> Fallback to muted autoplay

- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap_panorama/get_panorama_size.js
With arbitrarily small hot spots is does not make sense to scale the
panorama behond a certain point. Prevent dividing by zero.
> Limit panorama min scaling

- app/assets/stylesheets/pageflow/linkmap_page.scss
- app/assets/stylesheets/pageflow/linkmap_page/themes/default.scss
Remove unused overridden styles from base stylesheet.
Backport of #45 
REDMINE-15986
> Add theme variables for  circle and connector line colors

- app/assets/javascript/pageflow/linkmap_page/editor/models/area.js
- app/assets/javascript/pageflow/linkmap_page/editor/views/edit_area_view.js
- app/assets/javascript/pageflow/linkmap_page/editor/views/embedded/area_item_embedded_view.js
- app/assets/javascript/pageflow/linkmap_page/editor/views/embedded/area_masks_preview_embedded_view.js
- app/assets/javascript/pageflow/linkmap_page/editor/views/embedded/area_outlines_embedded_view.js
- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap/area_set_mask.js
- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap/color_map.js
- app/helpers/pageflow/linkmap_page/areas_helper.rb
- config/locales/new/color_map_component_id.de.yml
- config/locales/new/color_map_component_id.en.yml
- lib/pageflow/linkmap_page/paperclip_processors/color_mask.rb
- lib/pageflow/linkmap_page/paperclip_processors/colors.rb
- lib/tasks/pageflow_linkmap_page_tasks.rake
- spec/helpers/pageflow/linkmap_page/areas_helper_spec.rb
Change Rake-Task to not override mask_perma_id but add color_map_component_id to linkmap area configuration.
For all read operations on mask_perma_id color_map_component_id now takes precedence, with mask_perma_id as fallback.
For write operations only color_map_component_id is used.
This way all mask_perma_ids will gradually be converted to color_map_component_ids.
REDMINE-15982
> Add compatibility to 1.5 changes

- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap_pan_zoom.js
Even for hotspots that are bigger than the viewport, we can never
scale the panorama wrapper with a factor < 1. Since it is resized to
always fit either vertically or horizontally, we would otherwise
create letter or pillar boxes.
REDMINE-16562
> Prevent letter boxes in pan zoom

- lib/pageflow/linkmap_page/paperclip_processors/colors.rb
- spec/pageflow/linkmap_page/paperclip_processors/colors_spec.rb
Apparently ImageMagick now returns 8 digit hex color strings also when
alpha channel is 1. The linkmap functionality should not care about
this change. Colors are only processed once and basically act as names
from then on. Some specs dependent on concrete color codes, though.
Remove trailing FF in 8 digit color strings to return to previous
output format.
> Fix specs depending on color parsing with ImageMagick 6.9

- app/assets/javascript/pageflow/linkmap_page/editor/models/page_configuration_mixin.js
- app/jobs/pageflow/linkmap_page/process_source_image_file_job.rb
- app/models/pageflow/linkmap_page/masked_image_file.rb
- app/models/pageflow/linkmap_page/processed_image_file.rb
- pageflow-linkmap-page.gemspec
- spec/factories/image_file.rb
- spec/models/pageflow/linkmap_page/color_map_file_spec.rb
- spec/models/pageflow/linkmap_page/masked_image_file_spec.rb
- spec/support/config/active_job.rb
- spec/support/config/resque.rb
- spec/support/config/timecop.rb
Instead of creating color map and masked images only after their
prerequisites (i.e. source image files, color map files of masked
image files) are ready, add pending result to
`ProcessSourceImageFileJob` which causes job to be retried after a few
seconds.
This simplifies editor js code and handles a formerly missing case
that the source image file has not finished uploading yet. (REDMINE-16880)
This will also simplify processing files when importing a revision
(REDMINE-16811) since the order in which files are processed does not
matter.
> Make processing jobs wait for prerequisites

- db/migrate/20190724114801_delete_orphaned_generated_image_files.rb
Since running the migration added new problems to the complex
handling of linkmap pages, we decided to leave the data as is
and postpone cleaning up generated files with missing source files.
REDMINE-17136
REDMINE-17009
> Delete cleanup migration

- db/migrate/20190724114801_delete_orphaned_generated_image_files.rb
Backport of #68
Since running the migration added new problems to the complex
handling of linkmap pages, we decided to leave the data as is
and postpone cleaning up generated files with missing source files.
REDMINE-17136
REDMINE-17009
> Delete cleanup migration (2.6 Backport)

- app/assets/javascript/pageflow/linkmap_page/page_type.js
- app/assets/javascript/pageflow/linkmap_page/widgets/hover_video.js
- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap.js
- config/locales/de.yml
- config/locales/en.yml
REDMINE-17335
On mobile devices:
- Linkmap page background video autoplays without audio 
- Linkmap page hover video autoplays with audio when user clicks the hover area
> Enabled video autoplay for mobile devices.

- app/assets/javascript/pageflow/linkmap_page/editor/models/area.js
- app/assets/javascript/pageflow/linkmap_page/editor/models/new_area_file_selection_handler.js
When creating a new area or looking up the target of an area, audio
files were referenced by id instead of perma id. After creating the
area, the file input was therefore empty. Selecting a file via the
file input caused the area list thumbnail to display a missing
indicator instead of the pictogram.
REDMINE-17787
> Use perma id for audio hotspot files

- app/assets/javascript/pageflow/linkmap_page/editor/models/area.js
- app/assets/javascript/pageflow/linkmap_page/editor/models/new_area_file_selection_handler.js
When creating a new area or looking up the target of an area, audio
files were referenced by id instead of perma id. After creating the
area, the file input was therefore empty. Selecting a file via the
file input caused the area list thumbnail to display a missing
indicator instead of the pictogram.
REDMINE-17787
> Use perma id for audio hotspot files (2.7 Backport)

- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap_pan_zoom.js
When using the guided hotspot navigation mode, clicking a hotspot that
triggers a page change using a scroll transition causes the slideshow
container (`div.entry.slideshow`) to change its scroll position
(`scrollLeft`/`scrollTop`). In some cases, once the animation finishes
the current page remains partly outside the viewport. Reproducible in
Chrome 89 and Firefox 88.
Clicking the page background (which also activates the current hotspot
in pan/zoom mode) does not cause this behavior. As a workaround, we
therefore keep area pointer events disabled in pan/zoom mode and rely
only on activating hotspots via clicking the background.
The actual root cause remains unknown.
REDMINE-18737
> Prevent slideshow container from scrolling out of view

- Gemfile
- bin/rspec
- lib/pageflow-linkmap-page.rb
- lib/pageflow/linkmap_page/engine.rb
- pageflow-linkmap-page.gemspec
> Rails 6 support
