- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap_panorama.js
Measure page instead of window.
> Prevent overlays to be displayed behind editor bar

- README.md
clarify instruction  where to enable the new function
> explicitly note to enable the feature

- pageflow-linkmap-page.gemspec
Add pessimistic version constraints to development dependencies.
> Add support for pageflow-external-links 1.x

- Gemfile
- pageflow-linkmap-page.gemspec
- spec/controllers/pageflow/linkmap_page/mask_sprites_controller_spec.rb
Also remove unused teaspoon Gemfile item.
> Ensure Pageflow 12 is used in tests

- CHANGELOG.md
- app/assets/javascript/pageflow/linkmap_page/editor/models/page_configuration_mixin.js
- app/assets/javascript/pageflow/linkmap_page/editor/models/stored_mask_sprite.js
- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap.js
- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap/color_map.js
- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap/image_data.js
- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap/remote_image.js
- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap_panorama.js
- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap_panorama/get_panorama_size.js
- app/assets/stylesheets/pageflow/linkmap_page.scss
- app/assets/stylesheets/pageflow/linkmap_page/themes/default.scss
- app/views/pageflow/linkmap_page/page.html.erb
- config/locales/new/masks.de.yml
- config/locales/new/masks.en.yml
- lib/pageflow/linkmap_page/version.rb
* Improve mask image processing
* Improve touch indicator and loading spinner for external pages
> Improve mask features of hotspot page

- app/assets/stylesheets/pageflow/linkmap_page/themes/default.scss
Typo variables of the overlay can now be addressed in custom themes.
> Typographie variables for overlay section

- Gemfile
- app/controllers/pageflow/linkmap_page/mask_sprites_controller.rb
- db/migrate/20170330201200_create_mask_sprites.rb
- pageflow-linkmap-page.gemspec
- spec/controllers/pageflow/linkmap_page/mask_sprites_controller_spec.rb
- spec/spec_helper.rb
- spec/support/config/devise.rb
- spec/support/config/factory_bot.rb
* Rails 5
* FactoryBot
* Remove StateMachine dependency
> Migrate to Pageflow 13

- app/assets/javascript/pageflow/linkmap_page/page_type.js
Backport of #39 
REDMINE-15771
> Fallback to muted autoplay 

- app/assets/javascript/pageflow/linkmap_page/editor/views/edit_area_view.js
- app/assets/javascript/pageflow/linkmap_page/editor/views/embedded/mobile_info_box_embedded_view.js
- app/assets/javascript/pageflow/linkmap_page/page_type.js
- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap_paginator.js
- app/assets/stylesheets/pageflow/linkmap_page.scss
- app/views/pageflow/linkmap_page/page.html.erb
- config/locales/new/page_transitions.de.yml
- config/locales/new/page_transitions.en.yml
* Disable carousel pagination.
* Do not allow page change unless on first or last page of paginator.
* Display scroll indicator on last page instead of when returning to
first.
REDMINE-15848
> Integrate with horizontal slideshow navigation

- app/assets/stylesheets/pageflow/linkmap_page.scss
- app/assets/stylesheets/pageflow/linkmap_page/themes/default.scss
Remove unused overridden styles from base stylesheet.
REDMINE-15986
> Add theme variables for  circle and connector line colors

- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap_panorama.js
Prevent allowing scrolling in both directions even if
`add_environment` is false.
REDMINE-15778
> Handle scroller widget margin correctly

- app/assets/javascript/pageflow/linkmap_page/page_type.js
- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap_scroll_indicators.js
Scroll indicators suggest there is more to discover than there
actually is.
REDMINE-15778
> Only show scroll indicators if at least 20% of panorama is hidden

- app/helpers/pageflow/linkmap_page/areas_helper.rb
- app/views/pageflow/linkmap_page/areas/_div.html.erb
- app/views/pageflow/linkmap_page/page.html.erb
- spec/helpers/pageflow/linkmap_page/areas_helper_spec.rb
CSS selector did not apply. Set css class on same element in editor
and published entry.
REDMINE-16544
> Fix hiding linkmap info boxes

- app/assets/javascript/pageflow/linkmap_page/page_type.js
* Reset panorama position when emulation mode is toggled
* Activate panorama min scaling in phone emulation mode
* Do not warn about min scaling when guided navigation is used
REDMINE-15744
> Improve phone emulation support

- pageflow-linkmap-page.gemspec
- spec/integration/page_type_spec.rb
> Setup page type lint specs

- spec/factories/image_file.rb
For compatibility with pageflows direct-uploads refactoring
REDMINE-16119
> Adjust attachment name in image_file-factory

- app/assets/stylesheets/pageflow/linkmap_page.scss
- app/views/pageflow/linkmap_page/page.html.erb
- pageflow-linkmap-page.gemspec
> Adapt page DOM for Pageflow 14

- app/assets/stylesheets/pageflow/linkmap_page/themes/default.scss
> Use theme variable for overlay text color

- Gemfile
- app/assets/javascript/pageflow/linkmap_page/editor.js
- app/assets/javascript/pageflow/linkmap_page/editor/models/color_map_file.js
- app/assets/javascript/pageflow/linkmap_page/editor/models/generated_image_file.js
- app/assets/javascript/pageflow/linkmap_page/editor/models/masked_image_file.js
- app/assets/javascript/pageflow/linkmap_page/editor/models/page_configuration_mixin.js
- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap/color_map.js
- app/helpers/pageflow/linkmap_page/areas_helper.rb
- app/models/pageflow/linkmap_page/color_map_file.rb
- app/models/pageflow/linkmap_page/generated_image_file.rb
- app/models/pageflow/linkmap_page/masked_image_file.rb
- app/views/pageflow/linkmap_page/areas/_div.html.erb
- app/views/pageflow/linkmap_page/page.html.erb
- pageflow-linkmap-page.gemspec
- spec/helpers/pageflow/linkmap_page/areas_helper_spec.rb
Adapt to new module name and omit method stubs now defined in
Pageflow::ReusableFile
REDMINE-16809
REDMINE-16877
> Refactor ProcessedImageFile to GeneratedImageFile

- .travis.yml
> Specify mysql service for Travis build

- app/assets/javascript/pageflow/linkmap_page/editor/models/page_configuration_mixin.js
Do not create masked image file before color map file has been
persisted.
REDMINE-16810
> Wait for color map file to be persisted

- app/assets/javascript/pageflow/linkmap_page/editor/models/page_configuration_mixin.js
- app/assets/javascript/pageflow/linkmap_page/widgets/linkmap/color_map.js
> Use perma id for color map file and components

- app/assets/javascript/pageflow/linkmap_page/page_type.js
> Trigger media events for audio hotspots

- pageflow-linkmap-page.gemspec
> Add support for Pageflow 16

- app/models/pageflow/linkmap_page/color_map_file.rb
Required for Rails 7.1.
REDMINE-20487
> Declare serialize coder
